#!/bin/sh
# generate_sys_config alias_project_name targe_sys_config
# example: 
# generate_sys_config bk7231u config/sys_config.h

ARM_GCC_TOOLCHAIN=$(pwd)/Living_SDK/build/compiler/gcc-arm-none-eabi/Linux64/bin/
BEKEN_PATH=$(pwd)/Living_SDK/platform/mcu/$1/

if ["$2" == ""]; then
	old_sys_config=${BEKEN_PATH}config/sys_config.h
fi

if [ ! -d "config" ]; then
	mkdir ${BEKEN_PATH}config
fi

case $1 in
	bk7231u)
		new_sys_config=${BEKEN_PATH}beken/app/config/sys_config_bk7231u.h
		;;
	bk7231n)
		new_sys_config=${BEKEN_PATH}beken/app/config/sys_config_bk7231n.h
		;;
	bk7251)
		new_sys_config=${BEKEN_PATH}beken/app/config/sys_config_bk7251.h
		;;
	bk7231)
		new_sys_config=${BEKEN_PATH}beken/app/config/sys_config_bk7231.h
		;;
	*)
		new_sys_config=${BEKEN_PATH}beken/app/config/$1.h
esac

if [ -f $new_sys_config ]; then
	new_hash=`md5sum $new_sys_config | cut -d' ' -f 1`
else
	echo "$new_sys_config not exist!"
	exit 1
fi

if [ -f $old_sys_config ]; then
	old_hash=`md5sum $old_sys_config | cut -d' ' -f 1`
else
	old_hash=""
fi

#echo "hash($new_sys_config)=$new_hash"
#echo "hash($old_sys_config)=$old_hash"

if [ "$new_hash" != "$old_hash" ]; then
	cp -f $new_sys_config $old_sys_config
#	echo "update $old_sys_config with $new_sys_config"
fi

echo "  ${GREEN}GEN  ${BEKEN_PATH}.config${NC}"
rm -f ${BEKEN_PATH}.config
echo '#include "config/sys_config.h"' > ${BEKEN_PATH}config.c
sed -n '/^#define/p' ${BEKEN_PATH}config/sys_config.h | awk '{print $2}' | sort -d | uniq | awk '{print "valueOf_"$1"="$1}' >> ${BEKEN_PATH}config.c
echo "# Autogenerated by Makefile, DON'T EDIT" > ${BEKEN_PATH}.config
${ARM_GCC_TOOLCHAIN}arm-none-eabi-gcc -E ${BEKEN_PATH}config.c | grep '^valueOf_' | sed 's/valueOf_//' >> ${BEKEN_PATH}.config
sed -i '/_SYS_CONFIG_H_/d' ${BEKEN_PATH}.config
rm -f ${BEKEN_PATH}config.c
